// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rejudwrynbxoyzlrqqst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlanVkd3J5bmJ4b3l6bHJxcXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzY4NjUsImV4cCI6MjA3MDIxMjg2NX0.AMBlkzBMSlO8ohrDmNSPAl6zMKFIORBBo-iDDJQC8kI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});