// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ginifvflddhsltzbroeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbmlmdmZsZGRoc2x0emJyb2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0OTA4NzcsImV4cCI6MjA5MTA2Njg3N30.NaN-q4UjxXXCs5z3hFwqhIDyiZw-UNcS6--ZTJc5LI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});